### ISSUE TITLE
Does not compile on x86_64

### ISSUE THREAD

**Issue by DeweyTaylor** [pulkomandy/Sawteeth#42]
Attempts to compile as C++11 by default (unless I'm doing something wrong, which is very likely) and fails. I can provide specific errors if necessary, but I think this is a configuration issue. I just ran cmake ./ and then make

**Comment by alwayslivid** [comment]
Does not seem to be an issue on my end.

**Comment by pulkomandy** [comment]
Fixed in 8ea00f6d88cda5cb1a2caf13ff8cbbe852daa38f.
