### ISSUE TITLE
Weird splash screen behavior

### ISSUE THREAD

**Issue by alwayslivid** [pulkomandy/Sawteeth#48]
The splash screen of Sawteeth seems very clunky, resulting in a lack of clarity of the portrayed information. The splash screen should either get fixed or, alternatively (and preferably) get replaced with an About window, which should be implemented using the [built-in implementation of Haiku](https://github.com/haiku/haiku/blob/master/src/kits/interface/AboutWindow.cpp).

(The splash screen is also used as a substitute for an About window.)

Certain sections contain incorrect/outdated data as well.

![image](https://user-images.githubusercontent.com/30193966/72565525-b762cf00-38ba-11ea-869e-dd7e7095c092.png)

**Comment by pulkomandy** [comment]
I like it as it is.
