### ISSUE TITLE
Improve menu bar organization

### ISSUE THREAD

**Issue by alwayslivid** [pulkomandy/Sawteeth#50]
Most applications on Haiku follow a particular format when it comes to menu bars, as seen in the following examples:

![image](https://user-images.githubusercontent.com/30193966/72566253-268cf300-38bc-11ea-8233-059a02df6e4e.png)

![image](https://user-images.githubusercontent.com/30193966/72566291-386e9600-38bc-11ea-96ce-474515a495c9.png)

![image](https://user-images.githubusercontent.com/30193966/72566329-4c19fc80-38bc-11ea-84b8-398b3e972e65.png)

However, in the case of Sawteeth, one can observe that the menu bar does not really look as organized as one would expect from an advanced digital audio workspace.

![image](https://user-images.githubusercontent.com/30193966/72566191-1117c900-38bc-11ea-93ca-8c545dd8fa05.png)

This should be worked on and the menu bar has to be reimplemented in a user-friendlier fashion.

**Comment by pulkomandy** [comment]
I do not want to change this.
