### ISSUE TITLE
Certain menu items should not be clickable

### ISSUE THREAD

**Issue by alwayslivid** [pulkomandy/Sawteeth#51]
There are certain menu items that can be clicked, yet they do nothing when clicked.

Here's an example of an item:

![image](https://user-images.githubusercontent.com/30193966/72566532-a61ac200-38bc-11ea-8a3a-cf6623052fe7.png)

The items should either be rendered as unclickable, or they should be given some sort of corresponding, appropriate functionality.

**Comment by pulkomandy** [comment]
All submenus in Haiku are like this. A disabled submenu with active items makes no sense.
