### ISSUE TITLE
Replace "Let The Music" menu item

### ISSUE THREAD

**Issue by alwayslivid** [pulkomandy/Sawteeth#52]
This issue is relevant to #50.

Sawteeth currently has a menu item that allows people to control playback, which can be pretty difficult to use if you're an average user that does not regularly use keyboard shotcuts. Sawteeth plays loud generated sounds by default, so the playback must be made easier to control.

[ShowImage's ToolBarIcons](https://github.com/haiku/haiku/blob/master/src/apps/showimage/ToolBarIcons.cpp) implementation may be a good place to start exploring potential options.

**Comment by pulkomandy** [comment]
I do not want to change this.
