### ISSUE TITLE
Swapping instruments must be made easier

### ISSUE THREAD

**Issue by alwayslivid** [pulkomandy/Sawteeth#53]
This issue is relevant to #47.

I've spent a handful amount of time using the program, yet I still can't figure out how to apply or swap out instruments and use them in a specific channel.

As a person who has used other digital audio workstations (e.x. Ableton Live), where swapping instruments can be as simple as a selection and a keyboard shortcut, this can be overwhelming.

The user interface should be improved in order to make that piece of functionality that already exists within the program easier to access and use.

![image](https://user-images.githubusercontent.com/30193966/72567116-e0d12a00-38bd-11ea-951c-0befdde3bbe6.png)

**Comment by pulkomandy** [comment]
To use an instrument you just put its number in the "instrument number" column. This is how all protracker-like music programs work. It can't be easier.

**Comment by alwayslivid** [comment]
> To use an instrument you just put its number in the "instrument number" column next to a note. This is how all protracker-like music programs work. It can't be easier.

Got it, thanks.
