### ISSUE TITLE
No build instructions - repo version blasts noise

### ISSUE THREAD

**Issue by nPHYN1T3** [pulkomandy/Sawteeth#55]
So it's been a hot minute...maybe an hour since I touched anything Be. Went hunting for some old audio stuff, Sequitur, Sawteeth. The old html says APlayer can play st files but I can't find mention of such a player for BeOS or other. I think I remember it existing but man...that was 20 years ago. Any idea who/what can play st files outside Sawteeth because when I try to use Sawteeth is just blasts me with noise. I tried to build from source but there are no build instructions, no make file etc.

**Comment by pulkomandy** [comment]
Build uses cmake so the instructions are (I will update the readme):

cmake
make

If cmake is not available install it (on Haiku) with pkgman install cmd:cmake . If you are running BeOS or some other variant I'm not sure I want to provide support for that. If you run some other OS this probably won't work outside the box.

I think I have only tested the 32bit version, maybe the 64bit one still has problems (but at least the player code has been fixed). The only other app that can play st files is APlayer (current sources: https://github.com/pulkomandy/aplayer), and it uses the same code.

**Comment by nPHYN1T3** [comment]
I'll play around, thanks for the update. Make was installed but I had some issues with the new repo system. It wouldn't list cmake, but then said there were updates, then locked up heh. One thing after another. It will be interesting to see if I can build it and if it fixes the noise blasting.

**Comment by pulkomandy** [comment]
It works fine for me on 32bit haiku with both gcc2 and gcc8 (just made a fresh build to be sure). So I suspect a problem for the 64bit version only? (are you running a 64bit version of Haiku?)

**Comment by nPHYN1T3** [comment]
Yeah was on the 64bit. I may go back to 32 or just an original Be install if I fool around more as the only version I can find of Sequitur is 32bit. If I export a song as aiff it plays fine, but if you play things 'raw' in the program it just blasts noise with a occasional mild hit of what it actually sounds like buried in the hiss and crackle heh.

**Comment by pulkomandy** [comment]
The only part that's different between the AIFF export and the direct replay is where we send the data to the audio output using BSoundPlayer: https://github.com/pulkomandy/Sawteeth/blob/master/Source/stsp.cpp

And I see the problem there!

There is this:

`#ifdef __INTEL__`

which will not be set for x86_64, so the endianness used will be wrong. I'll fix that.

**Comment by nPHYN1T3** [comment]
JLG would be ashamed! heh. Cool you caught that though. That is one of those plain sight things I'd expect would be overlooked forever and drive you mad trying to figure out what is going wrong.

**Comment by nPHYN1T3** [comment]
Change to stsp.cpp worked like a charm. Thanks for your time...goes to play Spooky from the song files :)
